name: AutoCrop
author: WatsonLLC
description: Automatically re-plant crops
version: 1.1.0
api-version: 1.19
main: com.watsonllc.autocrop.AutoCrop
commands:
  autocrop:
    description: Autocrop command
    aliases: ac